### ISSUE TITLE
Cross build for Scala 2.13.0 milestones

### ISSUE THREAD

**Issue by TimMoore** [akka/alpakka-kafka#540]
It would be nice to have 2.13.0-M5 cross-built releases of Alpakka Kafka so downstream dependents (such as Lagom) can test with the 2.13 milestones.

Depends on (for test):
- [ ] https://github.com/embeddedkafka/embedded-kafka/issues/33
- [ ] https://issues.apache.org/jira/browse/KAFKA-7197

**Comment by 2m** [comment]
I was not able to run tests with `2.13.0-M3` because of https://github.com/manub/scalatest-embedded-kafka/issues/148

But I have released `0.22` for `2.13.0-M3` without running tests. Artifacts are on their way to Maven Central.

**Comment by TimMoore** [comment]
I still can't find the artifacts https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-kafka_2.13.0-M3/ (404)

**Comment by 2m** [comment]
Hm. They are in bintray (https://dl.bintray.com/akka/maven/com/typesafe/akka/akka-stream-kafka_2.13.0-M3/0.22/) and bintray GUI says that it has successfully synced it. Will have to investigate.

**Comment by ennru** [comment]
Time to pick this up for 2.13.0-M5.

Missing test dependencies:
- [ ] https://github.com/embeddedkafka/embedded-kafka/issues/33
- [ ] https://issues.apache.org/jira/browse/KAFKA-7197

**Comment by ennru** [comment]
Kafka is upgrading to 2.13 in https://github.com/apache/kafka/pull/5454

**Comment by ennru** [comment]
Fixed for 2.13.0-RC3 with #817.
[Snapshots](https://doc.akka.io/docs/alpakka-kafka/current/snapshots.html) will become available. We expect to release 1.0.4 once Scala 2.13.0 is out.
